# this file is used to run the smage-proxy, smage-agent, and smage-docs services.
services:
    smage-proxy:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: smage-proxy
        restart: unless-stopped
        command: ["proxy"]
        ports:
            - "8080:8080"
        networks: [smage-net]
        healthcheck:
            test: ["CMD", "curl", "-f", "http://localhost:8080/health"]
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 5s

    smage-agent:
        depends_on:
            smage-proxy:
                condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile
        container_name: smage-agent
        restart: unless-stopped
        command: ["agent"]
        networks: [smage-net]
        healthcheck:
            test: ["CMD", "smage", "anchors"]
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 5s

    smage-docs:
        depends_on:
            smage-agent:
                condition: service_healthy
        build:
            context: .
            dockerfile: Dockerfile
        container_name: smage-docs
        restart: unless-stopped
        command: ["docs"]
        networks: [smage-net]
        healthcheck:
            test: ["CMD", "smage", "anchors"]
            interval: 10s
            timeout: 3s
            retries: 3
            start_period: 5s

    smage-test:
        build:
            context: .
            dockerfile: Dockerfile
        container_name: smage-test
        command: ["sh", "-c", "smage anchors && smage docs && smage agent"]
        restart: "no"
        networks: [smage-net]

networks:
    smage-net:
