name: SMAGE Multi-Platform Build

on:
    workflow_dispatch:
    push:
        branches: [main]

jobs:
    linux-x64:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Build SMAGE Linux x64 binary
              run: pkg ./dist/smage/smage.js --targets node20-linux-x64 --output smage-linux-x64

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: smage-linux-x64
                  path: smage-linux-x64
    macos-arm64:
        runs-on: macos-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4
            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 20
            - name: Install dependencies
              run: npm install
            - name: Build project
              run: npm run build
            - name: Build SMAGE macOS ARM64 binary
              run: pkg ./dist/smage/smage.js --targets node20-macos-arm64 --output smage-macos-arm64

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: smage-macos-arm64
                  path: smage-macos-arm64

    windows-x64:
        runs-on: windows-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v4

            - name: Setup Node
              uses: actions/setup-node@v4
              with:
                  node-version: 18

            - name: Install dependencies
              run: npm install

            - name: Build project
              run: npm run build

            - name: Build SMAGE Windows x64 binary
              run: pkg ./dist/smage/smage.js --targets node20-win-x64 --output smage-windows-x64.exe

            - name: Upload artifact
              uses: actions/upload-artifact@v4
              with:
                  name: smage-windows-x64
                  path: smage-windows-x64.exe
